version: '3.2'

services:

# -----------------------------------------------------------
# Automated test engine - tests the services from 'outside'
# -----------------------------------------------------------

  robot:
    build:
      context: .
      args:
        - "http_proxy=${HTTP_PROXY}"
        - "https_proxy=${HTTPS_PROXY}"
    user: "$USER_ID:$USER_ID"
    command: "--skiponfailure a11y /tests ${EXTRA_TESTS}"
    environment: 
      - "HOST=${TEST_HOST}"
      - "HOST_NO_AUTH=${HOST_NO_AUTH}"
      - "PUSH_GATEWAY=${PUSH_GATEWAY}"
      - "PROMETHEUS_JOB_NAME=${PROMETHEUS_JOB_NAME}"
      - "HTTP_PROXY=${HTTP_PROXY}"
      - "HTTPS_PROXY=${HTTPS_PROXY}"
      - "W3ACT_USERNAME=${W3ACT_USERNAME}"
      - "W3ACT_PASSWORD=${W3ACT_PASSWORD}"
      # URL to use when testing playback/APIs etc.
      - "TEST_URL=http://portico.bl.uk"
    volumes:
      - ./tests:/tests:ro
      - ./tests_destructive:/tests_destructive:ro
      - ./results:/results:rw
      # Adding these means we can run as a host user:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro


