version: '3.2'

services:

# -----------------------------------------------------------
# Automated test engine - tests the services from 'outside'
# -----------------------------------------------------------

  robot:
    build:
      context: .
      args:
        - "http_proxy=${HTTP_PROXY}"
        - "https_proxy=${HTTPS_PROXY}"
    user: "$USER_ID:$USER_ID"
    command: "/tests ${EXTRA_TESTS}"
    environment: 
      - "HOST=${TEST_HOST}"
      - "HOST_NO_AUTH=${HOST_NO_AUTH}"
      - "PUSH_GATEWAY=${PUSH_GATEWAY}"
      - "PROMETHEUS_JOB_NAME=${PROMETHEUS_JOB_NAME}"
      - "HTTP_PROXY=${HTTP_PROXY}"
      - "HTTPS_PROXY=${HTTPS_PROXY}"
      - "NO_PROXY=hub"
      - "W3ACT_USERNAME=${W3ACT_USERNAME}"
      - "W3ACT_PASSWORD=${W3ACT_PASSWORD}"
    volumes:
      - ./tests:/tests:ro
      - ./tests_destructive:/tests_destructive:ro
      - ./results:/results:rw
      # Adding these means we can run as a host user:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      - hub


# -----------------------------------------------------------
# Selenium test support
# See https://github.com/SeleniumHQ/docker-selenium
# -----------------------------------------------------------

  hub:
    image: selenium/standalone-firefox:4.1.2-20220208
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - "http_proxy=${HTTP_PROXY}"
      - "https_proxy=${HTTPS_PROXY}"
    #  - "no_proxy=hub"
    #  - "HUB_HOST=hub"
    #entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

