version: '3.2'

services:

# -----------------------------------------------------------
# Automated test engine - tests the services from 'outside'
# -----------------------------------------------------------

  robot:
    build:
      context: .
      args:
        - "http_proxy=${HTTP_PROXY}"
        - "https_proxy=${HTTPS_PROXY}"
    user: ${UID}
    command: "/tests ${EXTRA_TESTS}"
    environment: 
      - "HOST=${TEST_HOST}"
      - "HOST_NO_AUTH=${HOST_NO_AUTH}"
      - "PUSH_GATEWAY=${PUSH_GATEWAY}"
      - "PROMETHEUS_JOB_NAME=${PROMETHEUS_JOB_NAME}"
      - "HTTP_PROXY=${HTTP_PROXY}"
      - "HTTPS_PROXY=${HTTPS_PROXY}"
      - "W3ACT_USERNAME=${W3ACT_USERNAME}"
      - "W3ACT_PASSWORD=${W3ACT_PASSWORD}"
    volumes:
      - ./tests:/tests:ro
      - ./tests_destructive:/tests_destructive:ro
      - ./results:/results:rw

# -----------------------------------------------------------
# Selenium tests infrastructure
# Based on https://github.com/SeleniumHQ/docker-selenium/tree/3.141.59-zirconium#version-3-with-swarm-support
# -----------------------------------------------------------

  firefox:
    image: selenium/node-firefox:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - "http_proxy=${HTTP_PROXY}"
      - "https_proxy=${HTTPS_PROXY}"
      - "no_proxy=hub"
      - "HUB_HOST=hub"
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - "http_proxy=${HTTP_PROXY}"
      - "https_proxy=${HTTPS_PROXY}"
      - "no_proxy=hub"
      - "HUB_HOST=hub"
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  hub:
    image: selenium/hub:3.141.59-zinc
    ports:
      - "4444:4444"
    depends_on:
      - firefox
      - chrome
